/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-06 02:57:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.pigeonMarket.product.model.vo.*;
import com.pigeonMarket.category.model.vo.*;
import com.pigeonMarket.member.model.vo.Member;

public final class purchaseInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/purchase/../common/foot.jsp", Long.valueOf(1567646697356L));
    _jspx_dependants.put("/views/purchase/../common/menubar.jsp", Long.valueOf(1567646697357L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.pigeonMarket.category.model.vo");
    _jspx_imports_packages.add("com.pigeonMarket.product.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pigeonMarket.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	ArrayList<ProductSale> prList = (ArrayList<ProductSale>)request.getAttribute("prList");
	ArrayList<Attachment> fileList = (ArrayList<Attachment>)request.getAttribute("fileList");
	
	int sum = 0;
	String strpNo = "";
	String strprice = "";
	
	for(int i = 0; i<prList.size(); i++){
		sum = sum + prList.get(i).getPrice();
		if(i == prList.size()-1){
			strpNo += prList.get(i).getProductOkNo();
			strprice += prList.get(i).getPrice();
		}else{
			strpNo += prList.get(i).getProductOkNo() + ",";
			strprice += prList.get(i).getPrice() + ",";
		}
		
	}
	

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.textAtea th {\r\n");
      out.write("\t\tpadding: 0.3em 0.3em;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 1em;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tp {\r\n");
      out.write(" \t\tdisplay: block;\r\n");
      out.write("   \t\tmargin-block-start: 0em;\r\n");
      out.write("   \t\tmargin-block-end: 0em;\r\n");
      out.write("   \t\tmargin-inline-start: 0px;\r\n");
      out.write("   \t\tmargin-inline-end: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#titleImg{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:40%;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t#cancel, #payment{\r\n");
      out.write("\t\t height: 50px;\r\n");
      out.write("\t\t text-align:center;\r\n");
      out.write("\t\t font-size: 1.5em;\t\t\t\t \r\n");
      out.write("\t\t padding: 10px 0px;\r\n");
      out.write("\t\t color: white;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #cancel{\t \r\n");
      out.write("\t\tbackground: burlywood;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #payment{\t \r\n");
      out.write("\t\tbackground:cornflowerblue;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #cancel:hover, #payment:hover{\r\n");
      out.write("\t\t cursor: pointer;\r\n");
      out.write("\t\t }\t\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");

	Member loginUser = (Member)session.getAttribute("loginUser");
	
	// 세션에 담겨있는 메세지 받기
	String msg = (String)session.getAttribute("msg");
	
	String contextPath = request.getContextPath();
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html>\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("                <title>Insert title here</title>\r\n");
      out.write("                <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("                <link rel=\"shortcut icon\" href=\"dulgi.ico\">\r\n");
      out.write("                <link rel=\"icon\" href=\"dulgi.ico\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function showPopup() {\r\n");
      out.write("                        window.open(\"login.html\", \"a\", \"width=350, height=450, left=600, top=50\");\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                <script>\r\n");
      out.write("                    var msg = \"");
      out.print( msg );
      out.write("\";\r\n");
      out.write("                    $(function() {\r\n");
      out.write("                        if (msg != \"null\") {\r\n");
      out.write("                            alert(msg);\r\n");
      out.write("\r\n");
      out.write("                            //세션에 담긴 메세지 한번만 출력하고 삭제하기\r\n");
      out.write("                            ");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                    })\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <header id=\"header\">\r\n");
      out.write("                    <h1><a href=\"");
      out.print( request.getContextPath());
      out.write("\">처음으로</a></h1>\r\n");
      out.write("                    <nav id=\"nav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"icon solid fa-angle-down\">메뉴</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"generic.html\">소개</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/event.eo\">이벤트</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/inquiry.in\">문의사항</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/inquirylist.in\">관리자 문의사항</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/review.re\">리뷰</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/myPage.me\">mypage</a></li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">관리자메뉴</a>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member.mim\">회원 정보 관리</a></li>\r\n");
      out.write("                                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/black.bl\">블랙리스트 관리</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Option Three</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Option Four</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><input type=\"button\" value=\"Login\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/test.us'\"></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Scripts -->\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/util.js\"></script>\r\n");
      out.write("                <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
      out.write("\r\n");
      out.write("\t<section id=\"main\" class=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h2>주문/결제</h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"25%\" height=\"60px\">제품사진</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">판매자</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">상품제목</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">상품가격</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 for (ProductSale pr : prList){ 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");
for(Attachment at : fileList){
      out.write("\t<!-- 사진리스트 불러오기  -->\r\n");
      out.write("\t\t\t\t\t\t");
if(at.getProductNo() == pr.getProductOkNo()){ 
      out.write(" <!-- 사진상품번호 와 상품번호가 같을 경우 -->\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"titleImg\" src=\"");
      out.print( contextPath );
      out.write("/resources/thumbnail_uploadFiles/");
      out.print( at.getChangeName());
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print( pr.getpId() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print( pr.getProductTitle() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print( pr.getPrice() );
      out.write("원</th>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan='3' height=\"60px\" style=\"font-size:1.5em\"> 총 결제 금액</th>\r\n");
      out.write("\t\t\t\t<th style=\"font-size:1.5em\" >");
      out.print( sum );
      out.write("원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"25%\" height=\"60px\" > 배송지 &nbsp; 정보</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"userName\" value=\"");
      out.print( loginUser.getUserName() );
      out.write("\" readOnly></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"phone\" value=\"");
      out.print( loginUser.getPhone() );
      out.write("\" readOnly></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"address\" value=\"");
      out.print( loginUser.getAddress());
      out.write("\" readOnly></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"50%\" height=\"60px\" >결제 수단</th>\r\n");
      out.write("\t\t\t\t<th><div class=\"selectric\" >\r\n");
      out.write("\t\t\t\t\t\t<select id=\"pay_method\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">결제 수단</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"card\" selected=\"\">신용카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"trans\">실시간 계좌이체</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"vbank\">가상계좌</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"phone\">핸드폰소액결제</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th height=\"60px\" style=\"font-size:1.5em\">총결재금액</th>\r\n");
      out.write("\t\t\t\t<th style=\"font-size:1.5em\">");
      out.print( sum );
      out.write("원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><div id=\"cancel\"  onclick=\"history.go(-1);\">취소하기</div></th>\r\n");
      out.write("\t\t\t\t<th><div id=\"payment\" onclick=\" requestPay();\">결제하기</div></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t \r\n");
      out.write("\t\t var IMP = window.IMP; // 생략해도 괜찮습니다.\r\n");
      out.write("\t\tIMP.init(\"imp23410003\"); // \"imp00000000\" 대신 발급받은 \"가맹점 식별코드\"를 사용합니다.\r\n");
      out.write("\t\t\r\n");
      out.write("    \tfunction requestPay() {\r\n");
      out.write("      \t\t// IMP.request_pay(param, callback) 호출\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\tvar pm = $(\"#pay_method\").val(); \r\n");
      out.write("      \t\tvar price = ");
      out.print( sum);
      out.write(";\r\n");
      out.write("      \t\tvar userName = \"");
      out.print( loginUser.getUserName());
      out.write("\";\r\n");
      out.write("      \t\tvar phone = ");
      out.print( loginUser.getPhone());
      out.write(";\r\n");
      out.write("      \t\tvar address = \"");
      out.print( loginUser.getAddress());
      out.write("\";\r\n");
      out.write("      \t\tvar bId = \"");
      out.print( loginUser.getUserId());
      out.write("\";\r\n");
      out.write("      \t\tvar strpNo = \"");
      out.print( strpNo);
      out.write("\";\r\n");
      out.write("      \t\tvar email = \"");
      out.print( loginUser.getEmail() );
      out.write("\";\r\n");
      out.write("      \t\tvar strprice = \"");
      out.print( strprice);
      out.write("\";\r\n");
      out.write("      \t\tvar msg = \"\";\r\n");
      out.write("      \t\tvar href=\"\";\r\n");
      out.write("    \t\tIMP.request_pay({\r\n");
      out.write("    \t\t    pg : \"inicis\",\r\n");
      out.write("    \t\t    pay_method : pm,\r\n");
      out.write("    \t\t    name : '주문명:결제테스트',\r\n");
      out.write("    \t\t    amount : price,\r\n");
      out.write("    \t\t    buyer_name : userName,\r\n");
      out.write("    \t\t    buyer_tel : phone,\r\n");
      out.write("    \t\t    buyer_addr : address,\r\n");
      out.write("    \t\t    buyer_email : email\r\n");
      out.write("    \t\t    \r\n");
      out.write("    \t\t},  function(rsp) {\r\n");
      out.write("    \t\t    if ( rsp.success ) {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("    \t      \t\t\turl:\"insert.pc\", \r\n");
      out.write("    \t      \t\t\tdata : {impUid: rsp.imp_uid, bId:bId, strpNo:strpNo, strprice:strprice},\r\n");
      out.write("    \t      \t\t\ttype : \"post\",\r\n");
      out.write("    \t      \t\tsuccess : function(result){\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\terror : function(){\r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t    });\r\n");
      out.write("\t\t\t\t\tmsg = '결제가 완료 되었습니다.';\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/myPage.me\"\r\n");
      out.write("    \t\t    } else {\r\n");
      out.write("    \t\t        msg = '결제에 실패하였습니다.';\r\n");
      out.write("    \t\t        msg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("    \t\t        href=\"#\";\r\n");
      out.write("    \t\t    }\r\n");
      out.write("\r\n");
      out.write("    \t\t    alert(msg);\r\n");
      out.write("    \t\t    location.href= href;\r\n");
      out.write("    \t\t    \r\n");
      out.write("    \t\t});\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("            <ul class=\"icons\">\r\n");
      out.write("                <li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"icon brands fa-google-plus\"><span class=\"label\">Google+</span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"copyright\">\r\n");
      out.write("                <li>&copy; Korea.KH 학원.오늘도 평화롭조.</li>\r\n");
      out.write("                <li>E-mail: <a href=\"#\">1234@naver.com</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
