/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-03 14:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.pigeonMarket.product.model.vo.*;
import com.pigeonMarket.category.model.vo.*;
import com.pigeonMarket.member.model.vo.Member;

public final class purchaseInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/purchase/../common/foot.jsp", Long.valueOf(1567479183322L));
    _jspx_dependants.put("/views/purchase/../common/menubar.jsp", Long.valueOf(1567491433744L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.pigeonMarket.category.model.vo");
    _jspx_imports_packages.add("com.pigeonMarket.product.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pigeonMarket.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	ProductSale pr = (ProductSale)request.getAttribute("p");
	ArrayList<Attachment> fileList = (ArrayList<Attachment>)request.getAttribute("fileList");
	Attachment titleImg = fileList.get(0);

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.textAtea th {\r\n");
      out.write("\t\tpadding: 0.3em 0.3em;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 1em;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\tp {\r\n");
      out.write(" \t\tdisplay: block;\r\n");
      out.write("   \t\tmargin-block-start: 0em;\r\n");
      out.write("   \t\tmargin-block-end: 0em;\r\n");
      out.write("   \t\tmargin-inline-start: 0px;\r\n");
      out.write("   \t\tmargin-inline-end: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#titleImg{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:40%;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t#cancel, #payment{\r\n");
      out.write("\t\t height: 50px;\r\n");
      out.write("\t\t text-align:center;\r\n");
      out.write("\t\t font-size: 1.5em;\t\t\t\t \r\n");
      out.write("\t\t padding: 10px 0px;\r\n");
      out.write("\t\t color: white;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #cancel{\t \r\n");
      out.write("\t\tbackground: burlywood;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #payment{\t \r\n");
      out.write("\t\tbackground:cornflowerblue;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t #cancel:hover, #payment:hover{\r\n");
      out.write("\t\t cursor: pointer;\r\n");
      out.write("\t\t }\t\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	
	// 세션에 담겨있는 메세지 받기
	String msg = (String)session.getAttribute("msg");
	
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/css/main.css\" />\t\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"dulgi.ico\">\r\n");
      out.write("<link rel=\"icon\" href=\"dulgi.ico\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("  \t\tfunction showPopup() { window.open(\"login.html\", \"a\", \"width=350, height=450, left=600, top=50\"); }\r\n");
      out.write(" </script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar msg = \"");
      out.print( msg );
      out.write("\";\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tif(msg != \"null\"){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//세션에 담긴 메세지 한번만 출력하고 삭제하기\r\n");
      out.write("\t\t\t");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t\t\t\t<h1><a href=\"");
      out.print( request.getContextPath());
      out.write("\">처음으로</a></h1>\r\n");
      out.write("\t\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"icon solid fa-angle-down\">메뉴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"generic.html\">소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/event.eo\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/inquiry.in\">문의사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/inquirylist.in\">관리자 문의사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/review.re\">리뷰</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"mypage.html\">mypage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">관리자메뉴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member.mim\">회원 정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/black.bl\">블랙리스트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option Three</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option Four</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"button\" value=\"Login\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/test.us'\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"main\" class=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h2>주문/결제</h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<form action=\"\">\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"25%\" height=\"60px\">판매자</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">상품사진</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">상품제목</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">상품가격</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>");
      out.print( pr.getpId() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<img id=\"titleImg\" src=\"");
      out.print( contextPath );
      out.write("/resources/thumbnail_uploadFiles/");
      out.print( titleImg.getChangeName());
      out.write("\" >\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print( pr.getProductTitle() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print( pr.getPrice() );
      out.write("원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th height=\"60px\"  colspan=\"3\" style=\"text-align:right;\">총상품금액 </th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print( pr.getPrice() );
      out.write("원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th height=\"60px\"  colspan=\"3\"  style=\"text-align:right;\">배송비</th>\r\n");
      out.write("\t\t\t\t<th>3000원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th  height=\"60px\"  colspan=\"3\"  style=\"text-align:right;\">총 결제금액</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print( pr.getPrice() + 3000 );
      out.write("원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"25%\" height=\"60px\" > 배송지 &nbsp; 정보</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"userName\" value=\"아무개\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"phone\" value=\"010 7797 7310\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" > <input type=\"text\" name=\"address\" value=\"서울시....\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>배송메모</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\"  class=\"cost1\" ><input type=\"text\" name=\"memo\" value=\"\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table class=\"textAtea\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"50%\" height=\"60px\"  >결제 방법</th>\r\n");
      out.write("\t\t\t\t<th>신용카드</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>카드 종류</th>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<div class=\"selectric \">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">카드 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SHINHAN\" selected=\"\">신한</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KB\">KB국민</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SAMSUNG\">삼성</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"BC\">BC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"HYUNDAI\">현대</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"WOORI\">우리</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"HANA\">하나</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KEB\">하나(구, 외환)</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"NH\">NH채움</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"LOTTE\">롯데</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"CITI\">씨티</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KAKAO\">카카오뱅크</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KBANK\">케이뱅크</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"IBK\">IBK기업</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"GWANGJU\">광주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SUHYUP\">수협</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SHINHYUP\">신협</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"POST\">우체국카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"FSB\">저축은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"JUNBOOK\">전북</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"JEJU\">제주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KDB\">산은캐피탈</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"MG\">MG새마을카드</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>할부 기간</th>\r\n");
      out.write("\t\t\t\t<th><div class=\"selectric \" >\r\n");
      out.write("\t\t\t\t\t\t<select id=\"Card_month\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">할부 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\" selected=\"\">일시불</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">7개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">8개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\">11개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\">12개월</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th height=\"60px\" style=\"font-size:1.5em\">총금액</th>\r\n");
      out.write("\t\t\t\t<th style=\"font-size:1.5em\">33000원</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><div id=\"cancel\">취소하기</div></th>\r\n");
      out.write("\t\t\t\t<th><div id=\"payment\">결제하기</div></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t<ul class=\"icons\">\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-google-plus\"><span class=\"label\">Google+</span></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"copyright\">\r\n");
      out.write("\t\t<li>&copy; Korea.KH 학원.오늘도 평화롭조.</li><li>E-mail: <a href=\"#\">1234@naver.com</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
