/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
<<<<<<< HEAD
<<<<<<< HEAD
 * Generated at: 2019-09-03 13:51:03 UTC
=======
 * Generated at: 2019-09-02 14:09:09 UTC
>>>>>>> parent of e149df0... 1999
=======
 * Generated at: 2019-09-02 14:09:09 UTC
>>>>>>> parent of e149df0... 1999
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.pigeonMarket.product.model.vo.*;
import com.pigeonMarket.category.model.vo.*;
import com.pigeonMarket.member.model.vo.Member;

public final class productDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
<<<<<<< HEAD
<<<<<<< HEAD
    _jspx_dependants.put("/views/product/../common/menubar.jsp", Long.valueOf(1567491433744L));
    _jspx_dependants.put("/views/product/../common/foot.jsp", Long.valueOf(1567479183322L));
=======
    _jspx_dependants.put("/views/product/../common/menubar.jsp", Long.valueOf(1567430328955L));
    _jspx_dependants.put("/views/product/../common/foot.jsp", Long.valueOf(1567430602771L));
>>>>>>> parent of e149df0... 1999
=======
    _jspx_dependants.put("/views/product/../common/menubar.jsp", Long.valueOf(1567430328955L));
    _jspx_dependants.put("/views/product/../common/foot.jsp", Long.valueOf(1567430602771L));
>>>>>>> parent of e149df0... 1999
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.pigeonMarket.category.model.vo");
    _jspx_imports_packages.add("com.pigeonMarket.product.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pigeonMarket.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	ProductSale pr = (ProductSale)request.getAttribute("p");
	ArrayList<Attachment> fileList = (ArrayList<Attachment>)request.getAttribute("fileList");
	Attachment titleImg = fileList.get(0);

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t .detail{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 700px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.imgDiv{\t\t\t\t\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t\tmargin-right: auto;\r\n");
      out.write("\t}\t\t\t\r\n");
      out.write("\t.textsize > textarea {\r\n");
      out.write("\t\tresize: none;\r\n");
      out.write("\t\tfont-size: 0.7em;\r\n");
      out.write("\t}\r\n");
      out.write("\t#basket, #purchase, #black{\r\n");
      out.write("\t\t height: 50px;\r\n");
      out.write("\t\t text-align:center;\r\n");
      out.write("\t\t font-size: 1.5em;\t\t\t\t \r\n");
      out.write("\t\t padding: 10px 0px;\r\n");
      out.write("\t\t color: white;\r\n");
      out.write("\t }\r\n");
      out.write("\t#basket{\t \r\n");
      out.write("\t\tbackground: burlywood;\r\n");
      out.write("\t}\r\n");
      out.write("\t#purchase{\t \r\n");
      out.write("\t\tbackground:cornflowerblue;\r\n");
      out.write("\t}\r\n");
      out.write("\t#black{\r\n");
      out.write("\t\tbackground:tomato;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inquiry{\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tfont-size: 1.5em;\t\t\t\t \r\n");
      out.write("\t\tpadding: 30px 0px;\r\n");
      out.write("\t\tcolor: white;\t \r\n");
      out.write("\t\tbackground:darkgrey;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inFormation{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tborder-right:2px solid rgba(241, 218, 7, 0.945);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#question{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\t#basket:hover, #purchase:hover, #black:hover,#inFormation:hover,#question:hover\t{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	
	// 세션에 담겨있는 메세지 받기
	String msg = (String)session.getAttribute("msg");
	
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/css/main.css\" />\t\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"dulgi.ico\">\r\n");
      out.write("<link rel=\"icon\" href=\"dulgi.ico\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("  \t\tfunction showPopup() { window.open(\"login.html\", \"a\", \"width=350, height=450, left=600, top=50\"); }\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t\t\t\t<h1><a href=\"");
      out.print( request.getContextPath());
      out.write("\">처음으로</a></h1>\r\n");
      out.write("\t\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"icon solid fa-angle-down\">메뉴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"generic.html\">소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/list.no\">문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"mypage.html\">mypage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Submenu</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option One</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option Two</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option Three</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Option Four</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"button\" value=\"Login\" onclick=\"showPopup();\" /></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main\" class=\"container\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h2>상품구매</h2>\r\n");
      out.write("\t</header>\t\t\t\t\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table class=\"detail\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th rowspan=\"5\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<div class = \"img0\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"titleImg\" src=\"");
      out.print( contextPath );
      out.write("/resources/thumbnail_uploadFiles/");
      out.print( titleImg.getChangeName());
      out.write("\"  width = \"100%\" height = \"100%\" >\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<th width=\"12.5%\">제목</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\">");
      out.print( pr.getProductTitle() );
      out.write("</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>판매자ID</th>\t\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">");
      out.print( pr.getpId() );
      out.write("</th>\r\n");
<<<<<<< HEAD
<<<<<<< HEAD
      out.write("\t\t\t\t<th id=\"diaArea\"><div id =\"black\" onclick=\"blackUSer();\">신고하기</div></th>\t\t\t\t\t\r\n");
=======
      out.write("\t\t\t\t<th><a><div id =\"black\">신고하기</div></a></th>\t\t\t\t\t\r\n");
>>>>>>> parent of e149df0... 1999
=======
      out.write("\t\t\t\t<th><a><div id =\"black\">신고하기</div></a></th>\t\t\t\t\t\r\n");
>>>>>>> parent of e149df0... 1999
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>판매가격</th>\t\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">");
      out.print( pr.getPrice() );
      out.write("원</th>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>제품승인날짜</th>\t\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">");
      out.print( pr.getApprovalDate() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th></th>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
<<<<<<< HEAD
<<<<<<< HEAD
      out.write("\t\t\t\t<td colspan=\"2\" class=\"diaArea\"><a href=\"");
      out.print( contextPath);
      out.write("/insert.sm?pNo=");
      out.print( pr.getProductOkNo());
      out.write("\"><div id = \"basket\">장바구니</div></a></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"diaArea\"><a  href=\"");
      out.print( contextPath);
      out.write("/insertForm.pc?pNo=");
      out.print( pr.getProductOkNo());
      out.write("\"><div id = \"purchase\">구매</div></a></td>\t\t\t\r\n");
=======
      out.write("\t\t\t\t<td colspan=\"2\" ><a><div id = \"basket\">장바구니</div></a></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><a><div id = \"purchase\">구매</div></a></td>\t\t\t\r\n");
>>>>>>> parent of e149df0... 1999
=======
      out.write("\t\t\t\t<td colspan=\"2\" ><a><div id = \"basket\">장바구니</div></a></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><a><div id = \"purchase\">구매</div></a></td>\t\t\t\r\n");
>>>>>>> parent of e149df0... 1999
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"1\" id=\"inFormation\"><div>상품정보</div></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" id=\"question\"><div>상품문의</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"5\" style=\"border-top :2px solid rgba(241, 218, 7, 0.945)\">상품정보</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t<div class = \"imgArea\" alige= \"center\">\r\n");
      out.write("\t\t\t\t\t\t");
 for(int i=1; i<fileList.size(); i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class = \"imgDiv\" alige= \"center\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/thumbnail_uploadFiles/");
      out.print( fileList.get(i).getChangeName());
      out.write("\"   width=\"33%\" height=\"33%\"> </div>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t<div class = \"textsize\">\r\n");
      out.write("<pre>");
      out.print( pr.getProductContents());
      out.write("</pre>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"5\">상품문의</th>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<div class = \"textsize\">\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"3\"  id=\"qnaTextarea\" ></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><div id=\"inquiry\">문의하기</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\t\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction blackUser(){\r\n");
      out.write("\t\t\tvar reason = window.prompt(\"신고사유를 적어주세요\");\r\n");
      out.write("\t\t\tvar pId = ");
      out.print( pr.getpId() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/Insert.bl?reason=\" + reason + \"&pId=\"+pId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t<ul class=\"icons\">\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"icon brands fa-google-plus\"><span class=\"label\">Google+</span></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"copyright\">\r\n");
      out.write("\t\t<li>&copy; Korea.KH 학원.오늘도 평화롭조.</li><li>E-mail: <a href=\"#\">1234@naver.com</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
